# Generated by Django 2.2.7 on 2021-05-18 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('corona_positive_since', models.DateTimeField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=5)),
                ('last_plasma_donation', models.DateTimeField(blank=True, null=True)),
                ('vaccination_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. only 10 digits are allowed.", regex='^d{10}$')])),
                ('state', models.IntegerField(default=-1)),
                ('action_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='is_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_donner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
