# Generated by Django 2.2.7 on 2021-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210518_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donner',
            name='state',
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.IntegerField(default=-1),
        ),
    ]
