# Generated by Django 2.2.7 on 2021-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210518_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
