# Generated by Django 2.2.7 on 2021-05-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210518_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donner',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='donner',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Users'),
        ),
    ]
