# Generated by Django 2.2.7 on 2021-05-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210518_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donner',
            old_name='id',
            new_name='users',
        ),
    ]
