# Generated by Django 2.2.7 on 2021-05-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210518_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donner',
            new_name='Donor',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='is_donner',
            new_name='is_donor',
        ),
    ]
