# Generated by Django 2.2.7 on 2021-05-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210519_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='corona_positive_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_plasma_donation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
