# Generated by Django 2.2.7 on 2021-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210519_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='can_donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
